### PR TITLE
Add hint and help base field properties and fix placeholder

### PR DESCRIPTION
**Pull request by ryanscherler**
I figured rather than just file an issue - I went ahead and fixed it ;-) Let me know what you think?

### CODE REVIEW

**Comment by masterix21** [comment]
Hi @ryanscherler, could you fix the test errors, please?

**Comment by ryanscherler** [comment]
> Hi @ryanscherler, could you fix the test errors, please?

Yep will do - looks like the `$hint` is undefined. I'll get that fixed. 

@masterix21 Can you see about fixing this error though?

```
TypeError: Argument 7 passed to Masterix21\XBladeComponents\View\Components\Form\Field::__construct() must be of the type bool, null given, called in /home/runner/work/x-blade-components/x-blade-components/src/View/Components/Form/ToggleField.php on line 12
```

**Comment by masterix21** [comment]
> @masterix21 Can you see about fixing this error though?
> 
> ```
> TypeError: Argument 7 passed to Masterix21\XBladeComponents\View\Components\Form\Field::__construct() must be of the type bool, null given, called in /home/runner/work/x-blade-components/x-blade-components/src/View/Components/Form/ToggleField.php on line 12
> ```

It's simple. You have added new parameters to Field, but Number, Toggle and other components are extending the Field calling the parent::__constructor: you can fix it changing these fields __constructor to match the parent.

**Comment by ryanscherler** [comment]
> It's simple. You have added new parameters to Field, but Number, Toggle and other components are extending the Field calling the parent::__constructor: you can fix it changing these fields __constructor to match the parent.

Gotcha - added new constructor arguments and tests passed (locally). Pushing now.

**Comment by masterix21** [comment]
Thanks @ryanscherler

**Pull request merged**
